"""Alarms and Office Alerts — the two person-to-person feeds.

A notification is generated by the system, addressed to a FARM, and read by
whoever has access to that farm. These are the opposite, and the whole value
of keeping them separate is that the sender is known without reading the
message: an alarm is the barn calling, an office alert is the office calling.
So the tests that matter are the ones about who may write where, and whether
the message reaches a person rather than a farm.
"""

import uuid

import pytest

from app.models.models import Message, MessageChannel, UserRole


async def _alarm(client, **body):
    return await client.post("/messages/", json={"channel": "alarm", **body})


async def _office_alert(client, **body):
    return await client.post("/messages/", json={"channel": "office_alert", **body})


# ── who may write to which feed ──────────────────────────────────────

async def test_a_farm_owner_can_raise_an_alarm_to_their_technician(
    api, db, farm, make_user,
):
    tech = await make_user(UserRole.technician, "Route Tech")
    farm.assigned_technician_id = tech.id
    await db.flush()

    async with api("farm", farm_id=farm.id) as client:
        r = await _alarm(client, body="Cow in pen 4 is down, come today.")

    assert r.status_code == 201, r.text
    sent = r.json()
    # No recipient was named: an owner writing from their own farm is answered
    # by that farm's standing technician, which is the only person they know.
    assert sent["recipient_id"] == str(tech.id)
    assert sent["farm_id"] == str(farm.id)
    assert sent["channel"] == "alarm"


async def test_an_owner_cannot_post_to_the_office_alerts_feed(api, db, farm, make_user):
    """If an owner could post here, the feed would stop meaning "the office
    said so" — which is the only reason it exists apart from Alarms."""
    tech = await make_user(UserRole.technician)

    async with api("farm", farm_id=farm.id) as client:
        r = await _office_alert(client, body="Your route changed.", recipient_id=str(tech.id))

    assert r.status_code == 403
    assert "admin" in r.json()["detail"]


async def test_a_technician_cannot_post_to_either_feed(api, db, farm, make_user):
    """Both feeds are addressed TO technicians. A technician writing into them
    would be talking to themselves, and on the office feed would be putting
    words in the administrator's mouth."""
    other = await make_user(UserRole.technician)

    async with api("technician") as client:
        alarm = await _alarm(client, body="hello", recipient_id=str(other.id),
                             farm_id=str(farm.id))
        office = await _office_alert(client, body="hello", recipient_id=str(other.id))

    assert alarm.status_code == 403
    assert office.status_code == 403


async def test_an_administrator_can_raise_an_office_alert(api, db, make_user):
    tech = await make_user(UserRole.technician)
    admin = await make_user(UserRole.admin, "The Office")

    async with api("admin", user_id=admin.id) as client:
        r = await _office_alert(client, body="Start at Cedar Lane on Friday.",
                                recipient_id=str(tech.id))

    assert r.status_code == 201, r.text
    assert r.json()["sender_name"] == "The Office"
    assert r.json()["sender_role"] == "admin"


# ── addressing ───────────────────────────────────────────────────────

async def test_an_alarm_needs_somebody_to_answer_it(api, db, farm):
    """A farm with no technician assigned has nobody to raise an alarm to.
    Silently dropping it would be the worst outcome: the owner believes help
    is coming."""
    farm.assigned_technician_id = None
    await db.flush()

    async with api("farm", farm_id=farm.id) as client:
        r = await _alarm(client, body="Cow down.")

    assert r.status_code == 409
    assert "no technician" in r.json()["detail"].lower()


async def test_a_message_cannot_be_addressed_to_a_farm_owner(api, db, farm, make_user):
    """These feeds run one way. A message addressed to an owner would sit in a
    feed their app never opens."""
    owner = await make_user(UserRole.farm, "Owner")
    admin = await make_user(UserRole.admin)

    async with api("admin", user_id=admin.id) as client:
        r = await _office_alert(client, body="hello", recipient_id=str(owner.id))

    assert r.status_code == 422
    assert "technician" in r.json()["detail"]


async def test_an_unlinked_farm_account_cannot_raise_an_alarm(api, db, make_user):
    """A farm account with no farm has no barn to report from, and farm_id is
    taken from the account rather than the request precisely so it cannot
    claim someone else's."""
    async with api("farm", farm_id=None) as client:
        r = await _alarm(client, body="Cow down.")

    assert r.status_code == 409
    assert "not linked to a farm" in r.json()["detail"].lower()


async def test_an_owner_cannot_raise_an_alarm_about_another_farm(
    api, db, farm, make_user,
):
    """farm_id comes from the account, not the body — so naming a farm they do
    not own changes nothing rather than being honoured."""
    tech = await make_user(UserRole.technician)
    farm.assigned_technician_id = tech.id
    from app.models.models import Farm
    other = Farm(id=uuid.uuid4(), name="Somebody Else's", owner_name="X", herd_size=0)
    db.add(other)
    await db.flush()

    async with api("farm", farm_id=farm.id) as client:
        r = await _alarm(client, body="Cow down.", farm_id=str(other.id))

    assert r.status_code == 201, r.text
    assert r.json()["farm_id"] == str(farm.id)


# ── the feed itself ──────────────────────────────────────────────────

async def test_each_feed_returns_only_its_own_channel(api, db, farm, make_user):
    """Two feeds in one table: a leak between them would put the barn's
    emergency in the middle of the office's scheduling notes."""
    tech = await make_user(UserRole.technician)
    admin = await make_user(UserRole.admin)
    farm.assigned_technician_id = tech.id
    await db.flush()

    async with api("farm", farm_id=farm.id) as owner_client:
        await _alarm(owner_client, body="Cow down.")
    async with api("admin", user_id=admin.id) as admin_client:
        await _office_alert(admin_client, body="Route change.", recipient_id=str(tech.id))

    async with api("technician", user_id=tech.id) as tech_client:
        alarms = (await tech_client.get("/messages/?channel=alarm")).json()
        office = (await tech_client.get("/messages/?channel=office_alert")).json()

    assert [m["body"] for m in alarms] == ["Cow down."]
    assert [m["body"] for m in office] == ["Route change."]


async def test_a_technician_sees_only_their_own_messages(api, db, farm, make_user):
    mine = await make_user(UserRole.technician, "Mine")
    theirs = await make_user(UserRole.technician, "Theirs")
    admin = await make_user(UserRole.admin)

    async with api("admin", user_id=admin.id) as admin_client:
        await _office_alert(admin_client, body="For mine", recipient_id=str(mine.id))
        await _office_alert(admin_client, body="For theirs", recipient_id=str(theirs.id))

    async with api("technician", user_id=mine.id) as client:
        feed = (await client.get("/messages/?channel=office_alert")).json()

    assert [m["body"] for m in feed] == ["For mine"]


async def test_marking_read_is_the_recipients_alone(api, db, farm, make_user):
    """Read state is a column here rather than a join table because there is
    exactly one reader — so nobody else can clear their badge."""
    tech = await make_user(UserRole.technician)
    intruder = await make_user(UserRole.technician)
    admin = await make_user(UserRole.admin)

    async with api("admin", user_id=admin.id) as admin_client:
        message_id = (await _office_alert(
            admin_client, body="Read me", recipient_id=str(tech.id))).json()["id"]

    async with api("technician", user_id=intruder.id) as client:
        assert (await client.patch(f"/messages/{message_id}/read")).status_code == 404

    async with api("technician", user_id=tech.id) as client:
        first = await client.patch(f"/messages/{message_id}/read")
        second = await client.patch(f"/messages/{message_id}/read")

    assert first.status_code == 200
    assert first.json()["read_at"] is not None
    # Idempotent: two devices, or a double tap, must not move the timestamp.
    assert second.json()["read_at"] == first.json()["read_at"]


async def test_unread_counts_answer_both_badges_in_one_call(api, db, farm, make_user):
    tech = await make_user(UserRole.technician)
    admin = await make_user(UserRole.admin)
    farm.assigned_technician_id = tech.id
    await db.flush()

    async with api("farm", farm_id=farm.id) as owner_client:
        await _alarm(owner_client, body="One")
        await _alarm(owner_client, body="Two")
    async with api("admin", user_id=admin.id) as admin_client:
        await _office_alert(admin_client, body="Three", recipient_id=str(tech.id))

    async with api("technician", user_id=tech.id) as client:
        counts = (await client.get("/messages/unread-counts")).json()

    assert counts == {"alarm": 2, "office_alert": 1}


async def test_a_blank_body_is_refused_before_it_reaches_the_constraint(
    api, db, farm, make_user,
):
    """The table CHECKs for a non-blank body; a body of spaces would satisfy
    pydantic's min_length and then surface as a 500 instead of a 422."""
    tech = await make_user(UserRole.technician)
    farm.assigned_technician_id = tech.id
    await db.flush()

    async with api("farm", farm_id=farm.id) as client:
        r = await _alarm(client, body="   ")

    assert r.status_code == 422


# ── route changes ────────────────────────────────────────────────────

async def test_a_route_change_reaches_both_technicians(api, db, farm, make_user):
    """The one who most needs to know is the one being taken OFF the farm —
    and by the time the change is saved they can no longer see that farm's
    notifications at all. A farm-addressed alert would reach everyone except
    the person whose day just changed.
    """
    from sqlalchemy import select

    outgoing = await make_user(UserRole.technician, "Outgoing")
    incoming = await make_user(UserRole.technician, "Incoming")
    admin = await make_user(UserRole.admin)
    farm.assigned_technician_id = outgoing.id
    await db.flush()

    async with api("admin", user_id=admin.id) as client:
        r = await client.patch(
            f"/farms/{farm.id}", json={"assigned_technician_id": str(incoming.id)},
        )
    assert r.status_code == 200, r.text

    messages = (await db.execute(
        select(Message).where(
            Message.channel == MessageChannel.office_alert,
            Message.farm_id == farm.id,
        )
    )).scalars().all()
    by_recipient = {m.recipient_id: m.body for m in messages}

    assert set(by_recipient) == {outgoing.id, incoming.id}
    assert "no longer on your route" in by_recipient[outgoing.id]
    assert "added to your route" in by_recipient[incoming.id]


async def test_a_farm_edit_that_leaves_the_route_alone_says_nothing(
    api, db, farm, make_user,
):
    """Renaming a farm is not a route change. Announcing one every time
    anything is saved is how a feed becomes noise."""
    from sqlalchemy import select

    tech = await make_user(UserRole.technician)
    admin = await make_user(UserRole.admin)
    farm.assigned_technician_id = tech.id
    await db.flush()

    async with api("admin", user_id=admin.id) as client:
        r = await client.patch(f"/farms/{farm.id}", json={"name": "Renamed Farm"})
    assert r.status_code == 200, r.text

    messages = (await db.execute(
        select(Message).where(Message.farm_id == farm.id)
    )).scalars().all()
    assert messages == []


async def test_reassigning_a_single_day_names_the_day(api, db, farm, make_user):
    from datetime import timedelta

    from sqlalchemy import select

    from app.core.timeutils import local_today

    standing = await make_user(UserRole.technician, "Standing")
    relief = await make_user(UserRole.technician, "Relief")
    admin = await make_user(UserRole.admin)
    farm.assigned_technician_id = standing.id
    await db.flush()
    when = local_today() + timedelta(days=2)

    async with api("admin", user_id=admin.id) as client:
        r = await client.put(
            f"/farms/{farm.id}/visit-assignments",
            json={"visit_date": when.isoformat(),
                  "assigned_technician_id": str(relief.id)},
        )
    assert r.status_code == 200, r.text

    bodies = [
        m.body for m in (await db.execute(
            select(Message).where(Message.farm_id == farm.id)
        )).scalars().all()
    ]
    assert any(when.isoformat() in b and "added to your route" in b for b in bodies)
    assert any(when.isoformat() in b and "no longer on your route" in b for b in bodies)
