"""The two person-to-person feeds: Alarms and Office Alerts.

A Notification is generated by the system, addressed to a FARM, and several
people read it. These are the other direction: one person writes to one
technician, and nothing generates them but a person deciding to.

  Alarms        farm owner    -> technician   ("the cow in pen 4 is down")
  Office Alerts administrator -> technician   ("your route changed for Friday")

Why not a third `type` on notifications: read state there lives in a join
table because a farm notification has many readers, the delivery side effect
is an email to the FARM, and farm access governs who can see it. A message has
exactly one reader, no email, and is addressed to a person -- including a
person who may have just lost access to the farm it mentions, which is
precisely the case a farm-addressed notification cannot reach.
"""

import uuid
from typing import Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.models import Farm, Message, MessageChannel, User, UserRole


async def send(
    db: AsyncSession,
    channel: MessageChannel,
    sender_id: uuid.UUID,
    recipient_id: uuid.UUID,
    body: str,
    farm_id: Optional[uuid.UUID] = None,
    cow_id: Optional[uuid.UUID] = None,
) -> Message:
    """Queue one message. The caller commits."""
    message = Message(
        id=uuid.uuid4(),
        channel=channel,
        sender_id=sender_id,
        recipient_id=recipient_id,
        farm_id=farm_id,
        cow_id=cow_id,
        body=body.strip(),
    )
    db.add(message)
    return message


async def send_office_alert(
    db: AsyncSession,
    sender_id: uuid.UUID,
    recipient_id: Optional[uuid.UUID],
    body: str,
    farm_id: Optional[uuid.UUID] = None,
) -> Optional[Message]:
    """An administrator's message to one technician. No recipient, no message."""
    if recipient_id is None:
        return None
    return await send(
        db, MessageChannel.office_alert, sender_id, recipient_id, body, farm_id=farm_id,
    )


async def announce_route_change(
    db: AsyncSession,
    admin_id: uuid.UUID,
    farm: Farm,
    previous_technician_id: Optional[uuid.UUID],
    new_technician_id: Optional[uuid.UUID],
    when: Optional[str] = None,
) -> int:
    """Tell both technicians when a farm moves between them.

    Both, and by message rather than by notification, because the one who most
    needs to know is the one being taken OFF the farm -- and by the time the
    change is saved they can no longer see that farm's notifications at all.
    A farm-addressed alert would reach everyone except the person whose day
    just changed.
    """
    if previous_technician_id == new_technician_id:
        return 0

    day = f" on {when}" if when else ""
    sent = 0
    if previous_technician_id is not None:
        await send_office_alert(
            db, admin_id, previous_technician_id,
            f"{farm.name} is no longer on your route{day}.", farm_id=farm.id,
        )
        sent += 1
    if new_technician_id is not None:
        await send_office_alert(
            db, admin_id, new_technician_id,
            f"{farm.name} has been added to your route{day}.", farm_id=farm.id,
        )
        sent += 1
    return sent


async def default_alarm_recipient(db: AsyncSession, farm_id: uuid.UUID) -> Optional[uuid.UUID]:
    """Who an owner's alarm goes to when they do not name anyone: the farm's
    standing technician."""
    farm = await db.get(Farm, farm_id)
    return farm.assigned_technician_id if farm else None


async def is_technician(db: AsyncSession, user_id: uuid.UUID) -> bool:
    """Both feeds are addressed to technicians; admins may also be on the
    receiving end, since they cover routes too."""
    role = await db.scalar(select(User.role).where(User.id == user_id))
    return role in (UserRole.technician, UserRole.admin)
