"""alarms and office alerts, cow names, and the farm's self-service switches

Four changes from the Sept 17 client notes, all additive:

  * `messages` -- the Alarms (owner -> technician) and Office Alerts
    (administrator -> technician) feeds. These are NOT notifications with a
    new `type`: a notification is generated by the system, addressed to a
    FARM, and read by several people, so its read state lives in a join
    table. A message is written by one person to one technician, so read
    state is a column and the sender is the point of the thing.

  * `cows.name` -- a farm that names its cows wants to find and read them
    that way. The tag stays the identity (it is what carries the unique
    constraint and what the regulator knows her by); the name is an alias.

  * `farms.self_inject_needling` / `farms.self_vaccinate` -- some farms give
    the last hormone and the post-calving vaccine themselves. Off by default,
    so every existing farm keeps today's behaviour.

  * `needling_records.self_administered` -- marks the shot the FARMER gives.
    It is real work on a real date, so it stays on the protocol; it simply
    must never be counted onto the technician's Needling report.

RLS mirrors the API: a technician sees the messages addressed to them, a
sender sees what they sent, an admin sees everything. Without a policy the
table would be readable through PostgREST with the anon key that ships inside
the app -- which is how `bulls` went wrong in 0012.

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-20
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID

revision: str = "0015"
down_revision: Union[str, None] = "0014"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── cow name ──────────────────────────────────────────────────────
    op.add_column("cows", sa.Column("name", sa.String(), nullable=True))
    # Lookup by name has to be as quick as lookup by tag or the search box
    # scans the herd. Case-insensitive because nobody types a cow's name the
    # same way twice.
    op.execute("create index ix_cows_farm_name on cows (farm_id, lower(name))")

    # ── per-farm self-service ─────────────────────────────────────────
    op.add_column("farms", sa.Column(
        "self_inject_needling", sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.add_column("farms", sa.Column(
        "self_vaccinate", sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.add_column("needling_records", sa.Column(
        "self_administered", sa.Boolean(), nullable=False, server_default=sa.text("false")))

    # ── messages ──────────────────────────────────────────────────────
    # Created explicitly, then referenced with create_type=False: handing
    # create_table a bare sa.Enum makes it emit CREATE TYPE a second time and
    # the migration dies on "type already exists".
    sa.Enum("alarm", "office_alert", name="message_channel").create(
        op.get_bind(), checkfirst=True)
    message_channel = postgresql.ENUM(
        "alarm", "office_alert", name="message_channel", create_type=False)

    op.create_table(
        "messages",
        sa.Column("id", UUID(as_uuid=True), primary_key=True),
        sa.Column("channel", message_channel, nullable=False),
        sa.Column("sender_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("recipient_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("farm_id", UUID(as_uuid=True), sa.ForeignKey("farms.id", ondelete="CASCADE")),
        sa.Column("cow_id", UUID(as_uuid=True), sa.ForeignKey("cows.id", ondelete="CASCADE")),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True),
                  server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("length(btrim(body)) > 0", name="ck_messages_body_not_blank"),
    )
    # The feed query is always "my messages on this channel, newest first".
    op.execute(
        "create index ix_messages_recipient_channel on messages "
        "(recipient_id, channel, created_at desc)"
    )

    op.execute("alter table messages enable row level security")
    op.execute("""create policy "messages_read" on messages for select
        using (
            recipient_id = auth.uid()
            or sender_id = auth.uid()
            or get_my_role() = 'admin'
        )""")
    # Who may raise which feed is the whole distinction between them, so the
    # database enforces it rather than trusting the caller to pass the right
    # channel: an owner cannot post an office alert in the administrator's
    # name, and the sender is always the authenticated user.
    op.execute("""create policy "messages_write" on messages for insert
        with check (
            sender_id = auth.uid()
            and (
                (channel = 'alarm' and get_my_role() in ('farm', 'admin'))
                or (channel = 'office_alert' and get_my_role() = 'admin')
            )
        )""")
    # Marking read is the recipient's own business.
    op.execute("""create policy "messages_mark_read" on messages for update
        using (recipient_id = auth.uid())
        with check (recipient_id = auth.uid())""")


def downgrade() -> None:
    op.execute('drop policy if exists "messages_mark_read" on messages')
    op.execute('drop policy if exists "messages_write" on messages')
    op.execute('drop policy if exists "messages_read" on messages')
    op.drop_table("messages")
    sa.Enum(name="message_channel").drop(op.get_bind(), checkfirst=True)

    op.drop_column("needling_records", "self_administered")
    op.drop_column("farms", "self_vaccinate")
    op.drop_column("farms", "self_inject_needling")
    op.execute("drop index if exists ix_cows_farm_name")
    op.drop_column("cows", "name")
